CC = c++

CFLAGSE = -Wall -Wextra -Werror -std=c++98

NAME = megaphone

FILES = megaphone.cpp


all:$(NAME)

$(NAME): $(FILES)
	$(CC $(CFLAGSE) -o $(NAME)

clean:
	rm -f $(obj)

fclean: clean
	rm -f $(NAME)

re: fclean all
